AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3

Metrics/ClassLength:
  Exclude:
    - 'test/*.rb'
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
