assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo gem install pdd -v 0.20.5
  bundle install
release:
  script: |-
    bundle exec rake
    pdd -f /dev/null
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" zache.gemspec
    git add zache.gemspec
    git commit -m "Version set to ${tag}"
    gem build zache.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
    pdd -f /dev/null
deploy:
  script: |-
    echo 'There is nothing to deploy'
    exit -1
